Repository strawlab/iana-time-zone, pull requests merged in 2022-10, with the labels that each got.

#67 Refactor MacOS implementation a lot
  src/tz_macos.rs
Labels: Unsafe-Proposed, Tier-1

#69 Refactor Android property key `CStr` construction to add tests
  src/ffi_utils.rs
  src/lib.rs
  src/tz_android.rs
Labels: Unsafe-Proposed, Tier-2

#66 Implement for Haiku
  .clang-format
  .github/workflows/rust.yml
  Cargo.toml
  haiku/Cargo.toml
  haiku/LICENSE-APACHE
  haiku/LICENSE-MIT
  haiku/README.md
  haiku/build.rs
  haiku/src/implementation.cc
  haiku/src/interface.h
  haiku/src/lib.rs
  src/lib.rs
  src/platform.rs
  src/tz_haiku.rs
Labels: Unsafe-Proposed, Tier-3

#78 Scope 'push' GitHub Actions workflow trigger to 'main' branch
  .github/workflows/rust.yml
Labels: bug

#75 Get Haiku platform crate compiling on non-Haiku platforms
  .github/workflows/rust.yml
  Cargo.toml
  haiku/Cargo.toml
  haiku/build.rs
  haiku/src/implementation.cc
  haiku/src/lib.rs
Labels: Tier-3

#77 Remove unused import in android impl
  src/tz_android.rs
Labels: Tier-2

#79 CI: use old clang when needed
  .github/workflows/rust.yml
Labels: Tier-1
