Repository strawlab/iana-time-zone, pull requests merged in 2023-10, with the labels that each got.

#117 Use `windows-core` with embedded bindings via `windows-bindgen`
  .github/workflows/rust.yml
  Cargo.toml
  api_gen/Cargo.toml
  api_gen/src/main.rs
  bindings.txt
  src/Windows.rs
  src/tz_windows.rs
Labels: Unsafe-Proposed, Tier-1

#122 CI: run tests on older windows-core version
  .github/workflows/rust.yml
Labels: Tier-1

#121 Implement for GNU Hurd
  CHANGELOG.md
  src/lib.rs
Labels: Tier-3

#57 Support AIX operating system
  src/lib.rs
  src/platform.rs
  src/tz_aix.rs
Labels: Tier-3
