Repository strawlab/iana-time-zone, pull requests merged in 2025-03, with the labels that each got.

#152 Disable Android FFI helpers on non-Android targets
  src/ffi_utils.rs
Labels: Tier-2, Tier-3

#156 Update Unicode license in cargo deny config
  deny.toml
Labels: Tier-2

#154 Centralize timezone name buffer and increase max length to fix Apple bug
  haiku/src/lib.rs
  src/ffi_utils.rs
  src/tz_darwin.rs
Labels: enhancement, Tier-1

#153 Fix Apple timezone caching issue by resetting system timezone cache
  examples/get_timezone_loop.rs
  src/tz_darwin.rs
Labels: Unsafe-Proposed, Tier-1

#150 Implement for OpenHarmony
  CHANGELOG.md
  src/ffi_utils.rs
  src/lib.rs
  src/tz_ohos.rs
Labels: Unsafe-Proposed, Tier-3

#163 Address high and medium severity zizmor findings
  .github/workflows/rust.yml
  .github/workflows/zizmor.yaml
Labels: github_actions

#164 AIX: remove unused code
  src/tz_aix.rs
Labels: Tier-3

#131 Bump `windows-core` to `0.53-0.54` range
  .clippy.toml
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  api_gen/Cargo.toml
  src/Windows.rs
Labels: dependencies, Tier-1

#133 Bump `windows-core` to `0.56-0.61` range and regenerate with `0.59`
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.toml
  api_gen/Cargo.toml
  api_gen/src/main.rs
  bindings.txt
  src/Windows.rs
  src/tz_windows.rs
  src/windows_bindings.rs
Labels: dependencies, Tier-1
